cp

diff --git a/containers/bin/cli_scripts/cli/shim b/containers/bin/cli_scripts/cli/shim
--- a/containers/bin/cli_scripts/cli/shim
+++ b/containers/bin/cli_scripts/cli/shim
@@ -1,30 +1,100 @@
 #!/usr/bin/env bash
 
 help() {
-sed 's/^    //' << EOF
-    Command
-        cli shim
+    cat << EOF
+Command
+    cli shim
 
-    Summary
-        Prints the source for function 'shim'.
-        
-    Description
+Summary
+    Prints the source for function 'shim'.
+    
+Description
 
-    Arguments
+Arguments
 
-    Global Arguments
-        --help -h       : Show this message and exit.
-        --self-test     : Runs a self test.
+Global Arguments
+    --help -h       : Show this message and exit.
+    --self-test     : Runs a self test.
 EOF
 }
 
 main() {
-    echo "help() { echo \"Unexpected missing 'help' in ${BASH_SOURCE[1]}.\"; }"
-    echo "test() { return; }"
-    declare -f shim
+
+    # supress background processes from displaying their exit status upon completion.
+    # see https://mywiki.wooledge.org/BashFAQ/024
+    echo 'set +m'
+
+    # run the last segment of a pipeline in the current execution process, not a subshell.
+    # see https://mywiki.wooledge.org/BashFAQ/024
+    echo 'shopt -s lastpipe'
+
+    echo 'set -e'
+    echo 'set -u' 
+    # set -o pipefail
+
+    # If set, the pattern ‘**’ used in a filename expansion context will match all 
+    # files and zero or more directories and subdirectories. If the pattern is followed 
+    # by a ‘/’, only directories and subdirectories match.
+    echo 'shopt -s globstar'
+
+    # If the extglob shell option is enabled using the shopt builtin, 
+    # several extended pattern matching operators are recognized. 
+    echo 'shopt -s extglob'
+
+    # If set, Bash allows filename patterns which match 
+    # no files to expand to a null string, rather than themselves.
+    echo 'shopt -s nullglob' 
+
+    echo "help() { echo \"Unexpected missing 'help' in \${BASH_SOURCE[1]}.\"; }"
+    echo "self_test() { return; }"
+    cli::export cli
+    echo "shim() { cli::shim \"\$@\"; }"
 }
 
-shim() {
+cli::export_functions() {
+    local glob
+
+    for i in "$@"; do 
+        glob+="${i}::"
+    done
+
+    while read keyword flags name; do
+        if [[ "${name}" == ${glob}* ]]; then
+            declare -f "${name}"
+        fi
+    done < <(declare -F)
+}
+
+cli::export_variables() {
+    local -u glob
+
+    for i in "$@"; do 
+        glob+="${i}_"; 
+    done
+
+    for i in $(eval echo "\${!${glob}@}"); do
+        declare -p "${i}"
+    done
+}
+
+cli::export() {
+    cli::export_variables "$@"
+    cli::export_functions "$@"
+}
+
+# dry run support
+cli::source() {
+    if [[ "${arg_dry_run:=}" == "true" ]]; then 
+        # removes extra spaces which is typically what we want
+        while read; do echo ${REPLY}; done
+    else
+        if [[ "${arg_debug:=}" == "true" ]]; then set -x; fi
+        source /dev/stdin
+        if [[ "${arg_debug:=}" == "true" ]]; then set +x; fi
+    fi
+}
+
+cli::shim() {
 
     escape_args_then_call_as() {
         local user=$1
@@ -38,65 +108,54 @@ shim() {
         sudo su "${user}" -c "${args[*]}"
     }
 
-    # echo -- "${BASH_SOURCE[1]} :: ${FUNCNAME[1]}" "$@" > /dev/stderr
+    # implement known flags before verifying arguments
+    for i in "$@"; do
+        if [[ "${i}" == '-h' ]] || [[ "${i}" == '--help' ]]; then 
+            help; exit
+        elif [[ "${i}" == '--self-test' ]]; then
+            self_test; exit
+        fi
+    done
+    unset i
 
-    # declare well known variables
-    : ${arg_help:=false}
-    : ${arg_tokenize_help:=false}
-    : ${arg_parse_help:=false}
-    : ${arg_self_test:=false}
-    : ${arg_run_as:=}
-
-    # resolve well known aliases
-    if [[ "${1-}" == '-h' ]]; then
-        set -- '--help'
+    # resolve aliases, and verify arguments
+    if ! declare -F initialize > /dev/null; then
+        help \
+            | cli dsl tokenize \
+            | cli dsl parse \
+            | cli dsl emit \
+            | source /dev/stdin
     fi
 
-    # declare variables passed via the command line    
-    local name
-    local value
-    local args=( "$@" )
-    until (( $# == 0 )); do
-        name="$1"; shift
+    # declare well known variables
+    : ${arg_run_as:=}
 
-        # support flags; e.g. This '--help true' is the same '--help' 
-        if (( $# == 0 )) || [[ "$1" == --* ]]; then
-            value="true"
-        else
-            value="$1"; shift
-        fi
-
-        # map argument names to bash names; e.g. '--foo' ==> 'ARG_FOO'
-        name="${name#--}"
-        name="arg_${name/-/_}"
-
-        # declare non-exported, but global, bash variables
-        declare -g "${name}"="${value}"
-    done
+    local -a args=( "$@" )
+    initialize "$@"
 
     # implement well known features
     if [[ -n "${arg_run_as}" ]] && [[ ! "${arg_run_as}" == "$(whoami)" ]]; then
         escape_args_then_call_as "${arg_run_as}" "$0" "${args[@]}"
-    elif [[ "${arg_tokenize_help}" == 'true' ]]; then 
-        help | cli dsl help tokenize
-    elif [[ "${arg_parse_help}" == 'true' ]]; then 
-        help | cli dsl help tokenize | cli dsl help parse
-    elif [[ "${arg_help}" == 'true' ]]; then 
-        help
-    elif [[ "${arg_self_test}" == 'true' ]]; then 
-        test
     else
-        # *really* clean up
-        unset name
-        unset value
-        unset args
+        # clean up known arguments
         unset arg_run_as
-        unset arg_help
-        unset arg_tokenize_help
-        unset arg_parse_help
         unset arg_self_test
+        unset arg_help
+        unset args
         main
     fi
 }
 
-shim "$@"
+initialize() {
+    while (( $# > 0 )); do
+        case $1 in
+            '-h') arg_help=true ;;
+            '--help') arg_help=true ;;
+            *) echo "Unexpected argument $1."; exit 1 ;;
+        esac
+
+        shift
+    done
+}
+
+cli::shim "$@"
